# Generated by Django 4.1.1 on 2022-10-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='db_products_changed',
        ),
    ]
