# Generated by Django 4.1.1 on 2022-10-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='giver_name',
        ),
    ]
