# Generated by Django 4.1.1 on 2022-10-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_first_name_customer_giver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='giver_name',
            new_name='first_name',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='db_customers_changed',
        ),
    ]
